#!/usr/bin/env php
<?php

/*
 * --------------------------------------------------------------------
 * CodeIgniter 4 Spark CLI
 * --------------------------------------------------------------------
 */

define('SPARKED', true);

// Path to the front controller
define('FCPATH', __DIR__ . DIRECTORY_SEPARATOR . 'public' . DIRECTORY_SEPARATOR);

// Ensure current directory is pointing to the front controller's directory
chdir(FCPATH);

require FCPATH . '../app/Config/Paths.php';

$paths = new Config\Paths();

// Location of the framework bootstrap file.
require rtrim($paths->systemDirectory, '\\/ ') . DIRECTORY_SEPARATOR . 'bootstrap.php';

require_once SYSTEMPATH . 'Config/DotEnv.php';
(new CodeIgniter\Config\DotEnv(ROOTPATH))->load();

$app = Config\Services::codeigniter();
$app->initialize();

use CodeIgniter\CLI\Console;

$console = new Console();
$exitCode = $console->run();

exit($exitCode);
